import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Calendar, Home, Vote, Menu, Search, CircleUser } from "lucide-react";
import Link from "next/link";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SIDEBAR_KEYBOARD_SHORTCUT = "b"

function AppSidebar() {
  const items = [
    {
      title: "Home",
      url: "/",
      icon: Home,
    },
    {
      title: "Polls",
      url: "/polls",
      icon: Vote,
    },
    {
      title: "Calendar",
      url: "/calendar",
      icon: Calendar,
    },
    {
      title: "Search",
      url: "/search",
      icon: Search,
    },
    {
      title: "About",
      url: "/about",
      icon: CircleUser,
    },
  ];

  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="ghost" size="icon" className="md:hidden">
          <Menu className="h-6 w-6" />
        </Button>
      </SheetTrigger>
      <SheetContent side="left" className="w-64">
        <SheetHeader>
          <SheetTitle>Catalog Polling</SheetTitle>
        </SheetHeader>
        <nav className="flex flex-col gap-2 mt-4">
          {items.map((item) => (
            <Link
              key={item.title}
              href={item.url}
              className={cn(
                "flex items-center gap-2 px-4 py-2 text-sm rounded-md hover:bg-accent",
                "transition-colors duration-200"
              )}
            >
              <item.icon className="h-4 w-4" />
              {item.title}
            </Link>
          ))}
        </nav>
      </SheetContent>
    </Sheet>
  );
}

function DesktopSidebar() {
  const items = [
    {
      title: "Home",
      url: "/",
      icon: Home,
    },
    {
      title: "Polls",
      url: "/polls",
      icon: Vote,
    },
    {
      title: "Calendar",
      url: "/calendar",
      icon: Calendar,
    },
    {
      title: "Search",
      url: "/search",
      icon: Search,
    },
    {
      title: "About",
      url: "/about",
      icon: CircleUser,
    },
  ];

  return (
    <div className="hidden md:flex h-screen w-64 border-r bg-background">
      <nav className="flex flex-col gap-2 p-4 w-full">
        <div className="px-4 py-2">
          <h2 className="text-lg font-semibold">Catalog Pollings</h2>
        </div>
        {items.map((item) => (
          <Link
            key={item.title}
            href={item.url}
            className={cn(
              "flex items-center gap-2 px-4 py-2 text-sm rounded-md hover:bg-accent",
              "transition-colors duration-200"
            )}
          >
            <item.icon className="h-4 w-4" />
            {item.title}
          </Link>
        ))}
      </nav>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased w-screen`}
      >
        <div className="flex min-h-screen">
          <DesktopSidebar />
          <div className="flex-1">
            <div className="p-4 md:hidden z-50">
              <AppSidebar />
            </div>
            <main className="container mx-auto p-4">{children}</main>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}